import type { BlogPost } from '../../types'

export const posts: Record<string, Partial<BlogPost>> = {
  '0': {
    title: 'Las exportaciones chinas de vehículos eléctricos suben 45% en el 2.º trimestre de 2026',
    excerpt: 'Las exportaciones chinas de vehículos eléctricos alcanzaron un récord de 680.000 unidades en el 2.º trimestre de 2026, impulsadas por la demanda en Asia Central, Medio Oriente y Sudamérica. BYD, Chery y NIO lideran.',
    cat: 'Noticias del sector',
    content: '<p>Las exportaciones chinas de vehículos eléctricos alcanzaron un récord de 680.000 unidades en el segundo trimestre de 2026, un aumento del 45% interanual, según los últimos datos de la Asociación de Fabricantes de Automóviles de China (CAAM). El repunte responde a la creciente demanda en Asia Central, Medio Oriente y Sudamérica — mercados donde las marcas chinas de VE ganan cuota rápidamente gracias a precios competitivos y redes de servicio en expansión.</p><p>BYD siguió siendo el mayor exportador en volumen con 215.000 VE embarcados en el trimestre, seguida de Chery (98.000) y NIO (72.000). Cabe destacar que marcas de gama media como Leapmotor y Voyah mostraron el crecimiento más rápido, más que duplicando sus volúmenes frente al primer trimestre.</p><p>"La tendencia es clara: los VE chinos ya no son solo un fenómeno doméstico", señaló un portavoz de la CAAM. "Los compradores extranjeros eligen cada vez más las marcas chinas por su combinación de autonomía, tecnología y precio".</p><p>El propio volumen exportado por Cargration refleja esta tendencia: los modelos eléctricos representaron el 38% de todos los vehículos embarcados en el 2.º trimestre de 2026, frente al 24% un año antes. Entre los modelos populares: BYD Seal, NIO ET5 y Zeekr 001.</p><p>Para compradores interesados en importar VE chinos, Cargration ofrece soporte integral — desde la selección e inspección hasta el envío y la documentación aduanera. Contacte con nuestro equipo para precios y disponibilidad actuales.</p>'
  },
  '1': {
    title: 'Nuevas rutas marítimas hacia América Latina',
    excerpt: 'Cargration abre un servicio Ro-Ro directo de Shanghái a Santos y Buenos Aires, reduciendo el tránsito a 28 días. La nueva línea cubre 14 destinos en Brasil, Argentina, Chile y Perú.',
    cat: 'Logística',
    content: '<p>Cargration ha lanzado un nuevo servicio Ro-Ro (rodante) directo desde Shanghái a los principales puertos de América Latina, reduciendo el tiempo de tránsito a tan solo 28 días. La línea hace escala en Santos (Brasil), Buenos Aires (Argentina), San Antonio (Chile) y Callao (Perú), con conexiones a 10 destinos adicionales de la región.</p><p>Anteriormente, los vehículos con destino a América Latina requerían transbordo en puertos europeos o por el Canal de Panamá, lo que añadía de 10 a 15 días al tránsito. Este nuevo servicio directo elimina esos retrasos y reduce el riesgo de daños en la manipulación.</p><p>"América Latina es uno de nuestros mercados de mayor crecimiento", indica el director de logística de Cargration. "Este servicio directo significa que los compradores de São Paulo o Buenos Aires reciben sus vehículos más rápido y con menos puntos de manipulación".</p><p>El servicio opera cada dos semanas, con capacidad de hasta 4.500 vehículos por buque. Los clientes de Cargration reciben seguimiento en tiempo real y documentación digital durante toda la travesía.</p><p>Para una cotización personalizada a cualquier destino latinoamericano, contacte con nuestro equipo logístico vía WhatsApp o Telegram.</p>'
  },
  '2': {
    title: 'Guía completa: importar un auto usado desde China',
    excerpt: 'Recorrido paso a paso del proceso de importación — desde elegir el vehículo y coordinar la inspección hasta el despacho aduanero y la entrega en el puerto de su país.',
    cat: 'Guía del comprador',
    content: '<p>Importar un auto usado desde China es más simple de lo que la mayoría espera, pero el proceso implica varios pasos clave. Aquí tiene el recorrido completo, de la selección a la entrega.</p><h3>Paso 1: Explorar y elegir</h3><p>Comience navegando por el catálogo de Cargration, con más de 20.800 vehículos. Filtre por marca, tipo de carrocería, rango de precio y puerto de salida. Cada anuncio muestra el precio FOB — el costo del vehículo incluyendo inspección y documentación de exportación, listo para cargar en el puerto.</p><h3>Paso 2: Inspección y verificación</h3><p>Una vez elegido el vehículo, Cargration realiza una inspección de 200 puntos que cubre motor, transmisión, frenos, suspensión, electrónica, carrocería e interior. Recibirá un reporte fotográfico y en video antes de comprometerse con la compra. Para pedidos de alto valor también puede contratarse una inspección independiente.</p><h3>Paso 3: Compra y documentación</h3><p>Tras aprobar la inspección, Cargration prepara el contrato FOB, el certificado de exportación y el conocimiento de embarque. El pago se realiza por transferencia bancaria a la cuenta corporativa. Toda la documentación se prepara antes de que el vehículo llegue al puerto para evitar demoras.</p><h3>Paso 4: Envío y logística</h3><p>Los vehículos salen en contenedor marítimo o buque Ro-Ro desde uno de los ocho puertos: Tianjin, Shanghái, Guangzhou, Shenzhen, Ningbo, Dalian, Qingdao o Xiamen. El flete marítimo suele tardar de 25 a 45 días según el destino. Las rutas ferroviarias hacia Asia Central: 12 a 20 días.</p><h3>Paso 5: Aduana y entrega</h3><p>A la llegada al puerto de destino, usted o su agente aduanero completan el despacho con la documentación provista por Cargration. Los documentos originales se liberan contra comprobante de despacho o según lo acordado en el contrato.</p><p>¿Necesita ayuda en algún paso? El equipo multilingüe de Cargration está disponible vía WhatsApp o Telegram.</p>'
  },
  '3': {
    title: 'Cómo funciona la inspección de 200 puntos antes de exportar',
    excerpt: 'Cada vehículo exportado por Cargration supera una inspección documentada de 200 puntos: motor, transmisión, frenos, suspensión, electrónica, carrocería e interior.',
    cat: 'Empresa',
    content: '<p>Cada vehículo exportado por Cargration pasa por una rigurosa inspección de 200 puntos antes de ponerse a la venta. Esto es exactamente lo que cubre cada control:</p><p><strong>1. Motor y transmisión:</strong> prueba de compresión, niveles de fluidos, estado de correas y mangueras, funcionamiento de arranque y alternador, evaluación de ruidos del motor y calidad del cambio de marchas (auto y manual).</p><p><strong>2. Frenos y suspensión:</strong> medición del grosor de pastillas y discos, revisión de las líneas de freno, estado de amortiguadores, desgaste de pivotes y bujes.</p><p><strong>3. Electrónica:</strong> prueba de carga de batería, verificación de salida del alternador, funcionamiento de luces (altas, bajas, direccionales), sistema multimedia, verificación de sensores.</p><p><strong>4. Carrocería y pintura:</strong> medición de la uniformidad de las holguras, inspección de óxido y corrosión, lecturas de espesor de pintura (para detectar repasado o reparación por choque), revisión de cristales.</p><p><strong>5. Interior y equipamiento:</strong> estado de asientos y tapizados, climatización, elevalunas y cierres eléctricos, cotejo del odómetro con los registros de mantenimiento.</p><p><strong>6. Parte inferior y chasis:</strong> verificación de la geometría del chasis, estado del escape y las líneas de combustible y frenos, evaluación de corrosión inferior.</p><p><strong>7. Prueba de ruta:</strong> evaluación de 15 minutos que cubre aceleración, frenado, respuesta de dirección, calidad de cambios, ruidos de suspensión y estabilidad a alta velocidad.</p><p>El reporte completo de inspección se entrega a cada comprador antes de la compra. Por un cargo adicional, Cargration también coordina inspecciones de terceros independientes.</p>'
  },
  '4': {
    title: 'Top 10 de SUV chinos para exportación en 2026',
    excerpt: 'Nuestro ranking de los SUV chinos más demandados por compradores internacionales, basado en datos de exportación del 1.er trimestre de 2026, precios, fiabilidad y disponibilidad de repuestos.',
    cat: 'Noticias del sector',
    content: '<p>Los SUV chinos ganan popularidad entre los compradores internacionales por su relación precio-valor, equipamiento y fiabilidad. Con base en los datos de exportación del 1.er trimestre de 2026, análisis de precios y feedback de clientes, este es el top 10 de los SUV chinos más demandados para exportación.</p><ol><li><strong>BYD Song Plus DM-i</strong> — el SUV chino más vendido del mundo, conocido por su eficiencia híbrida y precio FOB competitivo cercano a $16.800.</li><li><strong>Chery Tiggo 8 Pro</strong> — insignia de 7 plazas con construcción sólida, popular en Rusia, Brasil y Medio Oriente. FOB: ~$14.500.</li><li><strong>Haval H6</strong> — fiabilidad probada y amplia red de repuestos lo hacen una elección constante. FOB: ~$12.300.</li><li><strong>Changan CS75 Plus</strong> — excelente valor a ~$10.600 FOB, muy popular en Asia Central y África.</li><li><strong>Geely Xingyue L</strong> — interior premium y plataforma derivada de Volvo, a ~$15.900 FOB.</li><li><strong>GAC GS8</strong> — SUV de gran tamaño imponente, ~$17.200 FOB.</li><li><strong>Chery Tiggo 9</strong> — nueva insignia 2026, equipamiento premium a ~$18.300 FOB.</li><li><strong>Haval Big Dog</strong> — estilo todoterreno rudo, popular en mercados con terreno difícil. FOB: ~$13.700.</li><li><strong>Exeed TXL</strong> — marca de lujo de Chery, competidor premium. ~$16.400 FOB.</li><li><strong>Jetour Dashing</strong> — opción económica con estilo moderno, ~$9.800 FOB.</li></ol><p>Todos los modelos listados están disponibles para exportación vía Cargration con inspección completa, documentación y envío. Contacte a nuestro equipo para stock y precios actualizados.</p>'
  },
  '5': {
    title: 'Entender el precio FOB: lo que los compradores deben saber',
    excerpt: 'El precio FOB (Free On Board) explicado — qué incluye, qué no incluye y cómo comparar cotizaciones FOB entre exportadores.',
    cat: 'Guía del comprador',
    content: '<p>FOB significa Free On Board ("puesto a bordo") — un término del comercio internacional que define el punto donde termina la responsabilidad del vendedor y comienza la del comprador. Entender exactamente qué incluye un precio FOB es esencial para comparar cotizaciones y presupuestar su importación.</p><h3>Qué incluye el FOB</h3><p>Cuando Cargration cotiza un precio FOB, incluye el costo del vehículo, la inspección previa a la exportación (200 puntos), limpieza y preparación básica, documentación de exportación y cargos de carga en el puerto de origen. El vehículo se entrega al costado del buque en el puerto acordado, despachado para exportación.</p><h3>Qué no incluye el FOB</h3><p>Flete marítimo, seguro de carga, gastos de manipulación en el puerto de destino, aranceles e impuestos de importación, despacho aduanero en destino, transporte terrestre desde el puerto de llegada, y cualquier modificación o reparación solicitada fuera del alcance de la inspección estándar.</p><h3>Cómo comparar cotizaciones FOB</h3><p>Al comparar precios FOB entre exportadores, verifique el alcance de la inspección incluida, si el precio contempla reparaciones menores de pintura y acabados, y qué documentación está incluida. Algunos exportadores cobran extra por el certificado de exportación o la emisión del conocimiento de embarque.</p><p>En Cargration, todos los precios FOB incluyen inspección, documentación y carga en puerto. El precio que ve en cada anuncio es el que paga — sin costos ocultos ni recargos de última hora.</p><p>Para un desglose completo de los costos de su importación, contacte al equipo de Cargration por WhatsApp o Telegram.</p>'
  }
}
