import type { BlogPost } from '../../types'

export const posts: Record<string, Partial<BlogPost>> = {
  '0': {
    title: 'Les exportations chinoises de VE bondissent de 45 % au T2 2026',
    excerpt: 'Les exportations chinoises de véhicules électriques ont atteint un record de 680 000 unités au T2 2026, portées par la demande en Asie centrale, au Moyen-Orient et en Amérique du Sud. BYD, Chery et NIO en tête.',
    cat: 'Actualités du secteur',
    content: '<p>Les exportations chinoises de véhicules électriques ont atteint un record de 680 000 unités au deuxième trimestre 2026, soit une hausse de 45 % sur un an, selon les dernières données de l\'Association chinoise des constructeurs automobiles (CAAM). Cette envolée s\'explique par la demande croissante en Asie centrale, au Moyen-Orient et en Amérique du Sud — des marchés où les marques chinoises de VE gagnent rapidement des parts grâce à des prix compétitifs et à des réseaux de service en expansion.</p><p>BYD reste le premier exportateur en volume avec 215 000 VE expédiés au T2, suivi de Chery (98 000) et NIO (72 000). Fait notable, les marques de milieu de gamme comme Leapmotor et Voyah affichent la croissance la plus rapide, plus que doublant leurs volumes par rapport au T1.</p><p>« La tendance est claire — les VE chinois ne sont plus un simple phénomène domestique », a déclaré un porte-parole de la CAAM. « Les acheteurs étrangers choisissent de plus en plus les marques chinoises pour leur combinaison d\'autonomie, de technologie et de prix. »</p><p>Le propre volume d\'exportation de Cargration reflète cette tendance : les modèles électriques représentaient 38 % des véhicules expédiés au T2 2026, contre 24 % un an plus tôt. Parmi les modèles populaires : BYD Seal, NIO ET5 et Zeekr 001.</p><p>Pour les acheteurs intéressés par l\'importation de VE chinois, Cargration offre un accompagnement complet — de la sélection et de l\'inspection jusqu\'à l\'expédition et la documentation douanière. Contactez notre équipe pour les prix et disponibilités actuels.</p>'
  },
  '1': {
    title: 'Nouvelles routes maritimes vers l\'Amérique latine',
    excerpt: 'Cargration ouvre un service Ro-Ro direct de Shanghai à Santos et Buenos Aires, réduisant le transit à 28 jours. La nouvelle ligne couvre 14 destinations au Brésil, en Argentine, au Chili et au Pérou.',
    cat: 'Logistique',
    content: '<p>Cargration a lancé un nouveau service Ro-Ro (roulier) direct depuis Shanghai vers les grands ports d\'Amérique latine, ramenant le temps de transit à 28 jours seulement. Le service fait escale à Santos (Brésil), Buenos Aires (Argentine), San Antonio (Chili) et Callao (Pérou), avec des correspondances vers 10 destinations supplémentaires de la région.</p><p>Auparavant, les véhicules destinés à l\'Amérique latine devaient être transbordés dans des ports européens ou via le canal de Panama, ajoutant 10 à 15 jours de transit. Ce nouveau service direct élimine ces délais et réduit les risques d\'avaries de manutention.</p><p>« L\'Amérique latine est l\'un de nos marchés à la plus forte croissance », indique le directeur logistique de Cargration. « Ce service direct permet aux acheteurs de São Paulo ou de Buenos Aires de recevoir leurs véhicules plus vite, avec moins de points de manutention. »</p><p>Le service opère toutes les deux semaines, chaque navire pouvant embarquer jusqu\'à 4 500 véhicules. Les clients Cargration bénéficient d\'un suivi en temps réel et de documents numériques pendant toute la traversée.</p><p>Pour un devis d\'expédition personnalisé vers n\'importe quelle destination latino-américaine, contactez notre équipe logistique via WhatsApp ou Telegram.</p>'
  },
  '2': {
    title: 'Guide complet : importer une voiture d\'occasion de Chine',
    excerpt: 'Pas à pas du processus d\'importation — du choix du véhicule et de l\'inspection à la douane et à la livraison au port dans votre pays.',
    cat: 'Guide acheteur',
    content: '<p>Importer une voiture d\'occasion de Chine est plus simple que ne le pensent la plupart des acheteurs, mais le processus comporte plusieurs étapes clés. Voici le parcours complet, de la sélection à la livraison.</p><h3>Étape 1 : Explorer et choisir</h3><p>Commencez par parcourir le catalogue Cargration : plus de 20 800 véhicules. Filtrez par marque, carrosserie, gamme de prix et port de départ. Chaque annonce affiche le prix FOB — coût du véhicule incluant l\'inspection et les documents d\'exportation, prêt au chargement au port.</p><h3>Étape 2 : Inspection et vérification</h3><p>Une fois le véhicule choisi, Cargration réalise une inspection en 200 points couvrant moteur, transmission, freins, suspension, électronique, carrosserie et habitacle. Un rapport photo et vidéo vous est remis avant tout engagement. Pour les commandes de valeur, une inspection par un tiers peut être organisée.</p><h3>Étape 3 : Achat et documentation</h3><p>Après validation de l\'inspection, Cargration prépare le contrat FOB, le certificat d\'exportation et le connaissement. Le paiement s\'effectue par virement bancaire sur le compte professionnel. Tous les documents sont préparés avant l\'arrivée du véhicule au port afin d\'éviter tout retard d\'expédition.</p><h3>Étape 4 : Expédition et logistique</h3><p>Les véhicules partent en conteneur maritime ou en navire roulier depuis l\'un des huit ports : Tianjin, Shanghai, Guangzhou, Shenzhen, Ningbo, Dalian, Qingdao ou Xiamen. Le fret maritime prend généralement 25 à 45 jours selon la destination. Les lignes ferroviaires vers l\'Asie centrale : 12 à 20 jours.</p><h3>Étape 5 : Dédouanement et livraison</h3><p>À l\'arrivée au port de destination, vous ou votre transitaire effectuez le dédouanement avec les documents fournis par Cargration. Les documents originaux sont libérés sur preuve du dédouanement ou selon les termes du contrat.</p><p>Besoin d\'aide à une étape ? L\'équipe support multilingue de Cargration est disponible via WhatsApp ou Telegram.</p>'
  },
  '3': {
    title: 'Comment fonctionne l\'inspection en 200 points avant export',
    excerpt: 'Chaque véhicule exporté par Cargration passe une inspection documentée en 200 points : moteur, transmission, freins, suspension, électronique, carrosserie et habitacle.',
    cat: 'Entreprise',
    content: '<p>Chaque véhicule exporté par Cargration subit une rigoureuse inspection en 200 points avant sa mise en vente. Voici précisément ce que couvre chaque contrôle :</p><p><strong>1. Moteur et transmission :</strong> test de compression, niveaux de fluides, état des courroies et durites, fonctionnement du démarreur et de l\'alternateur, évaluation du bruit moteur, qualité de passage des vitesses (auto et manuelle).</p><p><strong>2. Freins et suspension :</strong> mesure de l\'épaisseur des plaquettes et disques, contrôle de l\'étanchéité des circuits, état des amortisseurs, usure des rotules et silentblocs.</p><p><strong>3. Électronique :</strong> test de charge batterie, vérification de la sortie alternateur, fonctionnement de l\'éclairage (codes, feux de route, clignotants), système multimédia, vérification des capteurs.</p><p><strong>4. Carrosserie et peinture :</strong> mesure de la régularité des joints, recherche de rouille et corrosion, mesures d\'épaisseur de peinture (détection de repeinture ou réparation après accident), contrôle des vitrages.</p><p><strong>5. Habitacle et équipements :</strong> état des sièges et garnissages, climatisation, lève-vitres et verrouillages électriques, cohérence du kilométrage avec l\'historique d\'entretien.</p><p><strong>6. Dessous et châssis :</strong> vérification de la géométrie du châssis, état de l\'échappement, des lignes de carburant et de frein, évaluation de la corrosion du dessous.</p><p><strong>7. Essai routier :</strong> évaluation de 15 minutes couvrant accélération, freinage, réponse de la direction, qualité des passages de vitesse, bruits de suspension et stabilité à haute vitesse.</p><p>Un rapport d\'inspection complet est remis à chaque acheteur avant l\'achat. Moyennant des frais supplémentaires, Cargration organise aussi une inspection par des organismes tiers indépendants.</p>'
  },
  '4': {
    title: 'Top 10 des SUV chinois à l\'export en 2026',
    excerpt: 'Notre classement des SUV chinois les plus demandés par les acheteurs internationaux, basé sur les données d\'export T1 2026, les prix, la fiabilité et la disponibilité des pièces.',
    cat: 'Actualités du secteur',
    content: '<p>Les SUV chinois séduisent de plus en plus les acheteurs internationaux par leur rapport qualité-prix, leur équipement et leur fiabilité. Sur la base des données d\'export du T1 2026, de l\'analyse des prix et des retours clients, voici le top 10 des SUV chinois les plus demandés.</p><ol><li><strong>BYD Song Plus DM-i</strong> — le SUV chinois le plus vendu au monde, réputé pour son efficience hybride et son prix FOB compétitif autour de 16 800 $.</li><li><strong>Chery Tiggo 8 Pro</strong> — vaisseau amiral 7 places à la solide construction, populaire en Russie, au Brésil et au Moyen-Orient. FOB : ~14 500 $.</li><li><strong>Haval H6</strong> — fiabilité éprouvée et vaste réseau de pièces en font un choix constant. FOB : ~12 300 $.</li><li><strong>Changan CS75 Plus</strong> — excellent rapport qualité-prix à ~10 600 $ FOB, très prisé en Asie centrale et en Afrique.</li><li><strong>Geely Xingyue L</strong> — habitacle premium et plateforme dérivée de Volvo, à ~15 900 $ FOB.</li><li><strong>GAC GS8</strong> — grand SUV à la présence imposante, ~17 200 $ FOB.</li><li><strong>Chery Tiggo 9</strong> — nouveau fleuron 2026, équipements premium à ~18 300 $ FOB.</li><li><strong>Haval Big Dog</strong> — style baroudeur, apprécié sur les terrains difficiles. FOB : ~13 700 $.</li><li><strong>Exeed TXL</strong> — marque premium de Chery, concurrent haut de gamme. ~16 400 $ FOB.</li><li><strong>Jetour Dashing</strong> — option budgétaire au style moderne, ~9 800 $ FOB.</li></ol><p>Tous les modèles cités sont disponibles à l\'export via Cargration avec inspection complète, documentation et expédition. Contactez notre équipe pour les stocks et tarifs actuels.</p>'
  },
  '5': {
    title: 'Comprendre le prix FOB : ce que les acheteurs doivent savoir',
    excerpt: 'Le prix FOB (Free On Board) expliqué — ce qu\'il inclut, ce qu\'il exclut, et comment comparer les devis FOB entre exportateurs.',
    cat: 'Guide acheteur',
    content: '<p>FOB signifie Free On Board (« Franco à bord ») — un terme du commerce international définissant le point où la responsabilité du vendeur s\'arrête et celle de l\'acheteur commence. Comprendre précisément ce qu\'inclut un prix FOB est essentiel pour comparer les devis et budgétiser votre importation.</p><h3>Ce que le FOB inclut</h3><p>Lorsque Cargration annonce un prix FOB, il comprend le coût du véhicule, l\'inspection pré-export (200 points), le nettoyage et la préparation de base, la documentation d\'exportation et les frais de chargement au port d\'origine. Le véhicule est livré au bord du navire au port convenu, dédouané à l\'export.</p><h3>Ce que le FOB n\'inclut pas</h3><p>Le fret maritime, l\'assurance cargo, les frais de manutention au port de destination, les droits et taxes d\'importation, le dédouanement à destination, le transport terrestre depuis le port d\'arrivée, ainsi que toute modification ou réparation demandée au-delà des constats de l\'inspection standard.</p><h3>Comparer les devis FOB</h3><p>En comparant les prix FOB entre exportateurs, vérifiez l\'étendue de l\'inspection, si les petites réparations de peinture et de garnissage sont incluses, et quels documents sont fournis. Certains exportateurs facturent en sus le certificat d\'exportation ou la préparation du connaissement.</p><p>Chez Cargration, tous les prix FOB incluent inspection, documents et chargement au port. Le prix affiché sur chaque annonce est le prix payé — sans frais cachés ni suppléments de dernière minute.</p><p>Pour une ventilation complète des coûts de votre importation, contactez l\'équipe Cargration sur WhatsApp ou Telegram.</p>'
  }
}
