import type { BlogPost } from '../../types'

export const posts: Record<string, Partial<BlogPost>> = {
  '0': {
    title: 'Exportações de veículos elétricos da China crescem 45% no 2º tri de 2026',
    excerpt: 'As exportações chinesas de veículos elétricos atingiram recorde de 680.000 unidades no 2º tri de 2026, impulsionadas pela demanda na Ásia Central, Oriente Médio e América do Sul. BYD, Chery e NIO lideram.',
    cat: 'Notícias do setor',
    content: '<p>As exportações chinesas de veículos elétricos atingiram um recorde de 680.000 unidades no segundo trimestre de 2026, alta de 45% em relação ao ano anterior, segundo os dados mais recentes da Associação de Fabricantes de Automóveis da China (CAAM). O salto é impulsionado pela demanda crescente na Ásia Central, Oriente Médio e América do Sul — mercados onde as marcas chinesas de VE ganham rapidamente participação com preços competitivos e redes de assistência em expansão.</p><p>A BYD seguiu como maior exportadora em volume, com 215.000 VEs embarcados no trimestre, seguida por Chery (98.000) e NIO (72.000). Vale destacar que marcas intermediárias como Leapmotor e Voyah tiveram o crescimento mais acelerado, mais que dobrando seus volumes em relação ao 1º tri.</p><p>"A tendência é clara — os VEs chineses não são mais apenas um fenômeno doméstico", disse um porta-voz da CAAM. "Compradores no exterior escolhem cada vez mais as marcas chinesas pela combinação de autonomia, tecnologia e preço."</p><p>O próprio volume de exportação da Cargration reflete essa tendência: modelos elétricos representaram 38% de todos os veículos embarcados no 2º tri de 2026, ante 24% um ano antes. Entre os modelos populares: BYD Seal, NIO ET5 e Zeekr 001.</p><p>Para compradores interessados em importar VEs chineses, a Cargration oferece suporte completo — da seleção e inspeção ao transporte e documentação alfandegária. Fale com nossa equipe para preços e disponibilidade atuais.</p>'
  },
  '1': {
    title: 'Novas rotas marítimas para a América Latina',
    excerpt: 'A Cargration abre serviço Ro-Ro direto de Xangai para Santos e Buenos Aires, reduzindo o trânsito para 28 dias. A nova linha cobre 14 destinos no Brasil, Argentina, Chile e Peru.',
    cat: 'Logística',
    content: '<p>A Cargration lançou um novo serviço Ro-Ro (roll-on/roll-off) direto de Xangai aos principais portos da América Latina, reduzindo o tempo de trânsito para até 28 dias. A linha escala em Santos (Brasil), Buenos Aires (Argentina), San Antonio (Chile) e Callao (Peru), com conexões para mais 10 destinos na região.</p><p>Antes, veículos destinados à América Latina exigiam transbordo em portos europeus ou pelo Canal do Panamá, adicionando de 10 a 15 dias ao trânsito. O novo serviço direto elimina esses atrasos e reduz o risco de danos de movimentação.</p><p>"A América Latina é um dos nossos mercados de crescimento mais rápido", afirma o diretor de logística da Cargration. "Esse serviço direto significa que compradores em São Paulo ou Buenos Aires recebem seus veículos mais rápido e com menos pontos de manuseio."</p><p>O serviço opera quinzenalmente, com capacidade de até 4.500 veículos por navio. Clientes Cargration recebem rastreamento em tempo real e documentação digital durante toda a viagem.</p><p>Para uma cotação personalizada para qualquer destino latino-americano, fale com nossa equipe logística via WhatsApp ou Telegram.</p>'
  },
  '2': {
    title: 'Guia completo: importando um carro usado da China',
    excerpt: 'Passo a passo do processo de importação — da escolha do veículo e agendamento da inspeção ao desembaraço aduaneiro e entrega no porto do seu país.',
    cat: 'Guia do comprador',
    content: '<p>Importar um carro usado da China é mais simples do que a maioria imagina, mas o processo envolve etapas-chave. Veja o caminho completo, da seleção à entrega.</p><h3>Etapa 1: Pesquisar e escolher</h3><p>Comece navegando pelo catálogo da Cargration, com mais de 20.800 veículos. Filtre por marca, carroceria, faixa de preço e porto de saída. Cada anúncio mostra o preço FOB — custo do veículo incluindo inspeção e documentação de exportação, pronto para carregamento no porto.</p><h3>Etapa 2: Inspeção e verificação</h3><p>Escolhido o veículo, a Cargration realiza inspeção em 200 pontos cobrindo motor, transmissão, freios, suspensão, eletrônica, lataria e interior. Você recebe relatório com fotos e vídeos antes de fechar a compra. Para pedidos de alto valor, pode ser contratada inspeção independente.</p><h3>Etapa 3: Compra e documentação</h3><p>Após aprovação da inspeção, a Cargration prepara o contrato FOB, certificado de exportação e conhecimento de embarque. O pagamento é feito por transferência bancária para a conta corporativa. Toda a documentação fica pronta antes do veículo chegar ao porto, evitando atrasos.</p><h3>Etapa 4: Frete e logística</h3><p>Os veículos seguem em contêiner marítimo ou navio Ro-Ro de um dos oito portos: Tianjin, Xangai, Guangzhou, Shenzhen, Ningbo, Dalian, Qingdao ou Xiamen. O frete marítimo leva normalmente de 25 a 45 dias conforme o destino. Rotas ferroviárias para a Ásia Central: 12 a 20 dias.</p><h3>Etapa 5: Desembaraço e entrega</h3><p>Na chegada ao porto de destino, você ou seu despachante conclui o desembaraço com a documentação fornecida pela Cargration. Os originais são liberados mediante comprovação do desembaraço ou conforme o contrato.</p><p>Precisa de ajuda em alguma etapa? A equipe multilíngue da Cargration atende via WhatsApp ou Telegram.</p>'
  },
  '3': {
    title: 'Como funciona a inspeção em 200 pontos antes da exportação',
    excerpt: 'Todo veículo exportado pela Cargration passa por inspeção documentada em 200 pontos: motor, transmissão, freios, suspensão, eletrônica, lataria e interior.',
    cat: 'Empresa',
    content: '<p>Todo veículo exportado pela Cargration passa por rigorosa inspeção em 200 pontos antes de ser anunciado para venda. Veja exatamente o que cada verificação cobre:</p><p><strong>1. Motor e transmissão:</strong> teste de compressão, níveis de fluidos, estado de correias e mangueiras, funcionamento do motor de partida e alternador, avaliação de ruídos do motor e qualidade das trocas de marcha (auto e manual).</p><p><strong>2. Freios e suspensão:</strong> medição da espessura de pastilhas e discos, checagem das linhas de freio, condição dos amortecedores, desgaste de pivôs e buchas.</p><p><strong>3. Eletrônica:</strong> teste de carga da bateria, verificação da saída do alternador, função das luzes (faróis, lanternas, setas), sistema multimídia, conferência dos sensores.</p><p><strong>4. Lataria e pintura:</strong> medição da uniformidade das folgas, inspeção de ferrugem e corrosão, leitura da espessura da pintura (para identificar repintura ou reparo de colisão), conferência dos vidros.</p><p><strong>5. Interior e recursos:</strong> condição de bancos e estofados, ar-condicionado, vidros e travas elétricas, conferência do hodômetro com os registros de manutenção.</p><p><strong>6. Parte inferior e chassi:</strong> verificação do alinhamento estrutural, estado do escapamento e das linhas de combustível e freio, avaliação de corrosão sob o veículo.</p><p><strong>7. Teste de estrada:</strong> avaliação de 15 minutos cobrindo aceleração, frenagem, resposta da direção, qualidade das trocas, ruídos da suspensão e estabilidade em alta velocidade.</p><p>O relatório completo da inspeção é entregue a cada comprador antes da compra. Por taxa adicional, a Cargration também contrata inspeções independentes de terceiros.</p>'
  },
  '4': {
    title: 'Top 10 SUVs chineses para exportação em 2026',
    excerpt: 'Nosso ranking dos SUVs chineses mais procurados por compradores internacionais, com base nos dados de exportação do 1º tri de 2026, preços, confiabilidade e disponibilidade de peças.',
    cat: 'Notícias do setor',
    content: '<p>Os SUVs chineses conquistam cada vez mais compradores internacionais pelo custo-benefício, equipamentos e confiabilidade. Com base nos dados de exportação do 1º tri de 2026, análise de preços e feedback de clientes, este é o top 10 dos SUVs chineses mais demandados.</p><ol><li><strong>BYD Song Plus DM-i</strong> — o SUV chinês mais vendido do mundo, conhecido pela eficiência híbrida e preço FOB competitivo perto de US$ 16.800.</li><li><strong>Chery Tiggo 8 Pro</strong> — flagship de 7 lugares com construção robusta, popular na Rússia, Brasil e Oriente Médio. FOB: ~US$ 14.500.</li><li><strong>Haval H6</strong> — confiabilidade comprovada e ampla rede de peças fazem dele uma escolha consistente. FOB: ~US$ 12.300.</li><li><strong>Changan CS75 Plus</strong> — excelente custo-benefício a ~US$ 10.600 FOB, muito popular na Ásia Central e África.</li><li><strong>Geely Xingyue L</strong> — interior premium e plataforma derivada da Volvo, a ~US$ 15.900 FOB.</li><li><strong>GAC GS8</strong> — SUV de grande porte imponente, ~US$ 17.200 FOB.</li><li><strong>Chery Tiggo 9</strong> — novo flagship 2026, recursos premium a ~US$ 18.300 FOB.</li><li><strong>Haval Big Dog</strong> — visual off-road rústico, popular em mercados com terrenos difíceis. FOB: ~US$ 13.700.</li><li><strong>Exeed TXL</strong> — marca de luxo da Chery, concorrente premium. ~US$ 16.400 FOB.</li><li><strong>Jetour Dashing</strong> — opção econômica com estilo moderno, ~US$ 9.800 FOB.</li></ol><p>Todos os modelos listados estão disponíveis para exportação via Cargration, com inspeção completa, documentação e frete. Fale com nossa equipe sobre estoque e preços atualizados.</p>'
  },
  '5': {
    title: 'Entendendo o preço FOB: o que os compradores precisam saber',
    excerpt: 'Preço FOB (Free On Board) explicado — o que inclui, o que não inclui e como comparar cotações FOB entre exportadores.',
    cat: 'Guia do comprador',
    content: '<p>FOB significa Free On Board — termo do comércio internacional que define o ponto em que a responsabilidade do vendedor termina e a do comprador começa. Entender exatamente o que um preço FOB inclui é essencial para comparar cotações e planejar o orçamento da sua importação.</p><h3>O que o FOB inclui</h3><p>Quando a Cargration cita um preço FOB, ele inclui o custo do veículo, a inspeção pré-exportação (200 pontos), limpeza e preparação básica, documentação de exportação e taxas de carregamento no porto de origem. O veículo é entregue ao costado do navio no porto combinado, liberado para exportação.</p><h3>O que o FOB não inclui</h3><p>Frete marítimo, seguro de carga, taxas de movimentação no porto de destino, impostos e tributos de importação, desembaraço aduaneiro no destino, transporte terrestre a partir do porto de chegada e quaisquer modificações ou reparos solicitados além do escopo da inspeção padrão.</p><h3>Como comparar cotações FOB</h3><p>Ao comparar preços FOB entre exportadores, confira o escopo da inspeção, se pequenos reparos de pintura e acabamento estão inclusos e quais documentos são fornecidos. Alguns exportadores cobram extra pelo certificado de exportação ou pela emissão do conhecimento de embarque.</p><p>Na Cargration, todos os preços FOB já incluem inspeção, documentação e carregamento no porto. O preço exibido em cada anúncio é o preço pago — sem taxas escondidas ou sobretaxas de última hora.</p><p>Para um detalhamento completo dos custos da sua importação, fale com a equipe Cargration no WhatsApp ou Telegram.</p>'
  }
}
