import type { Testimonial } from '../types'

export const testimonialsI18n: Record<string, Record<number, string>> = {
  ru: {
    0: 'Отчёт об осмотре полностью совпал с состоянием машины по прибытии во Владивосток. Никаких сюрпризов и торга.',
    1: 'Документы были готовы ещё до отхода судна из порта. Таможня в Абиджане пройдена за два дня.',
    2: 'В этом году купил 14 машин для своей площадки. Каждая FOB-цена выдержала до финального инвойса.',
    3: 'Первая партия из 8 кроссоверов Chery пришла в Ташкент по ж/д за 18 дней. Трекинг-портал сильно помог спланировать запуск.',
    4: 'Команда нашла мне BYD Dolphin, которого даже не было в каталоге, и прислала видео со стоянки в Шанхае до подготовки.',
    5: 'Таможня в Карачи прошла гладко благодаря COO и коносаменту, пришедшим DHL раньше судна.',
    6: 'Мы импортировали через Cargration более 30 машин. Стабильное качество автомобилей и точность документов заставляют возвращаться.',
    7: 'Отчёт об осмотре выявил царапину, которой не было видно на фото. Сделали скидку без споров. Честная работа.',
    8: 'От первого сообщения до отхода судна — 9 дней. Для первого импорта из Грузии это невероятно.',
    9: 'Поддержка в WhatsApp ответила в 2 часа ночи по Пекину. Одно это решило вопрос выбора экспортёра.',
    10: 'Заказали 5 Zeekr для шоурума в Аммане. Трекинг от двери до двери позволил клиентам следить за поставкой.',
    11: 'Смешанную партию электромобилей и бензиновых кроссоверов консолидировали в один контейнер. Погрузку разделили идеально.',
    12: 'Мой первый импорт из Китая — меня сопровождали на каждом шаге. Машина приехала даже чище, чем я ожидал.',
    13: 'Цена была на $400 выше конкурента, пока я не учёл их платный осмотр и сбор за документы. FOB у Cargration оказался дешевле.'
  },
  fr: {
    0: 'Le rapport d\'inspection correspondait exactement à l\'état de la voiture à son arrivée à Vladivostok. Aucune surprise, aucune renégociation.',
    1: 'La documentation était prête avant même le départ du navire. Dédouanement à Abidjan en deux jours.',
    2: 'J\'ai acheté 14 véhicules pour mon parc cette année. Chaque devis FOB a été respecté jusqu\'à la facture finale.',
    3: 'Notre première commande de 8 SUV Chery est arrivée à Tachkent en 18 jours par le rail. Le portail de suivi nous a permis de planifier notre lancement sereinement.',
    4: 'L\'équipe m\'a trouvé une BYD Dolphin pas encore listée, avec vidéo depuis le parc de Shanghai avant sa préparation.',
    5: 'Le dédouanement à Karachi s\'est fait sans accroc grâce au certificat d\'origine et au connaissement arrivés par DHL avant le navire.',
    6: 'Nous avons importé plus de 30 unités via Cargration. La régularité de la qualité et l\'exactitude des documents nous font revenir.',
    7: 'Le rapport d\'inspection a repéré une rayure invisible sur les photos. Remise accordée sans discuter. Opération honnête.',
    8: 'Du premier message au départ du navire : 9 jours. Pour un premier import depuis la Géorgie, bluffant.',
    9: 'Le support WhatsApp a répondu à 2 h du matin, heure de Pékin. Cela a suffi à choisir Cargration plutôt qu\'un autre exportateur.',
    10: 'Nous avons commandé 5 Zeekr pour notre showroom d\'Amman. Le suivi porte-à-porte permettait à nos clients de suivre l\'expédition.',
    11: 'Une flotte mixte de VE et de SUV essence consolidée dans un seul conteneur. Répartition du chargement parfaitement gérée.',
    12: 'Premier import chinois pour moi, accompagné à chaque étape. La voiture est arrivée encore plus propre que prévu.',
    13: 'Le prix était 400 $ plus haut qu\'un concurrent jusqu\'à ce que j\'intègre ses frais d\'inspection et de documents. Le FOB de Cargration était en réalité moins cher.'
  },
  ar: {
    0: 'تطابق تقرير الفحص مع حالة السيارة عند وصولها فلاديفوستوك تمامًا. لا مفاجآت ولا إعادة تفاوض.',
    1: 'كانت المستندات جاهزة قبل مغادرة السفينة للميناء أصلًا. تم التخليص الجمركي في أبيدجان خلال يومين.',
    2: 'اشتريت 14 سيارة لمعرضي هذا العام. كل عرض سعر FOB صمد حتى الفاتورة النهائية.',
    3: 'وصلت أول دفعة من 8 سيارات Chery SUV إلى طشقند بالسكك الحديدية في 18 يومًا. بوابة التتبع سهّلت علينا تخطيط الإطلاق.',
    4: 'ساعدني الفريق في إيجاد BYD Dolphin لم تكن مدرجة بعد، وأرسلوا فيديو من ساحة شنغهاي قبل تجهيزها.',
    5: 'مرّ التخليص الجمركي في كراتشي بسلاسة بفضل شهادة المنشأ وسند الشحن اللذين وصلا عبر DHL قبل السفينة.',
    6: 'استوردنا أكثر من 30 سيارة عبر Cargration. الثبات في جودة السيارات ودقة المستندات يجعلنا نعود دائمًا.',
    7: 'اكتشف تقرير الفحص خدشًا لم يظهر في الصور. منحونا خصمًا دون جدال. تعامل أمين.',
    8: 'من أول رسالة إلى إبحار السفينة: 9 أيام. لأول استيراد لي من جورجيا، هذا مذهل.',
    9: 'رد دعم واتساب في الثانية صباحًا بتوقيت بكين. هذا وحده حسم اختياري بين شركات التصدير.',
    10: 'طلبنا 5 سيارات Zeekr لصالة العرض في عمّان. مكّننا التتبع الكامل عملاءنا من متابعة الشحنة خطوة بخطوة.',
    11: 'أسطول مختلط من الكهربائية وSUV البنزينة دُمجت جميعها في حاوية واحدة. أداروا تقسيم التحميل بإتقان.',
    12: 'أول استيراد لي من الصين ورافقوني في كل خطوة. وصلت السيارة أنظف مما توقعت.',
    13: 'كان السعر أعلى بـ400 دولار من منافس حتى حسبت رسوم فحصهم ومستنداتهم. تبين أن FOB لدى Cargration أرخص فعليًا.'
  },
  pt: {
    0: 'O relatório de inspeção correspondeu exatamente ao estado do carro na chegada a Vladivostok. Sem surpresas, sem renegociação.',
    1: 'A documentação ficou pronta antes mesmo do navio deixar o porto. Desembaraço em Abidjan em dois dias.',
    2: 'Comprei 14 unidades para meu lote este ano. Todas as cotações FOB se mantiveram até a fatura final.',
    3: 'Nosso primeiro pedido de 8 SUVs Chery chegou a Tashkent em 18 dias por ferrovia. O portal de rastreio facilitou planejar nosso lançamento.',
    4: 'A equipe encontrou uma BYD Dolphin que nem estava anunciada e enviou vídeo do pátio de Xangai antes da preparação.',
    5: 'O desembaraço em Carachi foi tranquilo graças ao certificado de origem e conhecimento de embarque que chegaram por DHL antes do navio.',
    6: 'Já importamos mais de 30 unidades pela Cargration. A consistência na qualidade dos veículos e na precisão dos documentos nos faz voltar sempre.',
    7: 'O laudo apontou um arranhão que as fotos não mostravam. Deram desconto sem discussão. Operação honesta.',
    8: 'Da primeira mensagem à partida do navio: 9 dias. Para um primeiro import vindo da Geórgia, impressionante.',
    9: 'O suporte no WhatsApp respondeu às 2 da manhã, horário de Pequim. Só isso já decidiu o exportador para mim.',
    10: 'Encomendamos 5 Zeekr para nosso showroom em Amã. O rastreio ponta a ponta permitiu aos clientes acompanhar o embarque.',
    11: 'Frota mista de elétricos e SUVs a gasolina consolidada em um único contêiner. Divisão de carga feita perfeitamente.',
    12: 'Meu primeiro import chinês e fui guiado durante todo o processo. O carro chegou mais limpo do que esperava.',
    13: 'O preço era US$ 400 acima de um concorrente até eu somar a taxa de inspeção e o cargo por documentos dele. O FOB da Cargration acabou sendo mais barato.'
  },
  es: {
    0: 'El reporte de inspección coincidió exactamente con el estado del auto al llegar a Vladivostok. Sin sorpresas ni renegociaciones.',
    1: 'La documentación estuvo lista antes incluso de que el barco saliera del puerto. Despacho en Abiyán en dos días.',
    2: 'Compré 14 unidades para mi lote este año. Todas las cotizaciones FOB se mantuvieron hasta la factura final.',
    3: 'Nuestro primer pedido de 8 SUV Chery llegó a Taskent en 18 días por ferrocarril. El portal de rastreo nos facilitó planificar el lanzamiento.',
    4: 'El equipo encontró una BYD Dolphin que ni siquiera estaba publicada y envió video del patio de Shanghái antes de prepararla.',
    5: 'El despacho en Karachi fue fluido gracias al certificado de origen y al conocimiento de embarque que llegaron por DHL antes que el buque.',
    6: 'Hemos importado más de 30 unidades con Cargration. La consistencia en calidad vehicular y precisión documental nos hace volver.',
    7: 'El reporte detectó un rayón que no se veía en las fotos. Aplicaron descuento sin discutir. Operación honesta.',
    8: 'Del primer mensaje a la salida del buque: 9 días. Para una primera importación desde Georgia, increíble.',
    9: 'El soporte de WhatsApp respondió a las 2 AM hora de Pekín. Eso solo ya definió mi elección de exportador.',
    10: 'Pedimos 5 Zeekr para nuestro showroom en Amán. El seguimiento puerta a puerta permitió a nuestros clientes seguir el envío.',
    11: 'Flota mixta de eléctricos y SUV a gasolina consolidada en un solo contenedor. División de carga perfecta.',
    12: 'Mi primera importación china y me acompañaron en todo el proceso. El auto llegó más limpio de lo esperado.',
    13: 'El precio estaba $400 sobre un competidor hasta sumar su cargo de inspección y documentos. El FOB de Cargration resultó más barato.'
  }
}
